[package]
name = "simple"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
runar_node = { path = "../../runar-node" }
runar_macros = { path = "../../runar-macros" }
runar_common = { path = "../../runar-common" }
async-trait = "0.1"
