/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** JavaScript service definition with action handlers */
export interface JsService {
  name: string
  path: string
  version?: string
  description?: string
  actions?: JsActions
}
/** JavaScript action handlers - using JsFunction that will be converted to ThreadsafeFunction */
export interface JsActions {
  echo?: (...args: any[]) => any
  add?: (...args: any[]) => any
  multiply?: (...args: any[]) => any
  subtract?: (...args: any[]) => any
  ping?: (...args: any[]) => any
  reverse?: (...args: any[]) => any
}
/** Main Node interface for JavaScript */
export declare class JsNode {
  /** Synchronous constructor. Internally blocks on the async `Node::new`. */
  constructor()
  start(): Promise<void>
  stop(): Promise<void>
  request(path: string, payload?: JsonValue | undefined | null): Promise<JsonValue>
  publish(topic: string, data?: JsonValue | undefined | null): Promise<void>
  addService(jsService: JsService): Promise<void>
}
