// Auto-generated by cbindgen for runar_ffi

#ifndef RUNAR_FFI_H
#define RUNAR_FFI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct RNAPIKeysInner RNAPIKeysInner;

typedef struct RNAPITransportInner RNAPITransportInner;

typedef struct RNAPIRnError {
  int32_t code;
  const char *message;
} RNAPIRnError;

typedef struct RNAPIFfiKeysHandle {
  struct RNAPIKeysInner *inner;
} RNAPIFfiKeysHandle;

typedef struct RNAPIFfiTransportHandle {
  struct RNAPITransportInner *inner;
} RNAPIFfiTransportHandle;

void rn_free(uint8_t *_p, size_t _len);

void rn_string_free(const char *s);

int32_t rn_last_error(char *out, size_t out_len);

void rn_set_log_level(int32_t level);

int32_t rn_keys_encrypt_with_envelope(void *keys,
                                      const uint8_t *data,
                                      size_t data_len,
                                      const char *network_id_or_null,
                                      const uint8_t *const *profile_pks,
                                      const size_t *profile_lens,
                                      size_t profiles_count,
                                      uint8_t **out_eed_cbor,
                                      size_t *out_len,
                                      struct RNAPIRnError *err);

int32_t rn_keys_decrypt_envelope(void *keys,
                                 const uint8_t *eed_cbor,
                                 size_t eed_len,
                                 uint8_t **out_plain,
                                 size_t *out_len,
                                 struct RNAPIRnError *err);

int32_t rn_discovery_new_with_multicast(void *keys,
                                        const uint8_t *options_cbor,
                                        size_t options_len,
                                        void **out_discovery,
                                        struct RNAPIRnError *err);

void rn_discovery_free(void *discovery);

int32_t rn_discovery_init(void *discovery,
                          const uint8_t *options_cbor,
                          size_t options_len,
                          struct RNAPIRnError *err);

int32_t rn_discovery_start_announcing(void *discovery, struct RNAPIRnError *err);

int32_t rn_discovery_stop_announcing(void *discovery, struct RNAPIRnError *err);

int32_t rn_discovery_shutdown(void *discovery, struct RNAPIRnError *err);

int32_t rn_discovery_update_local_peer_info(void *discovery,
                                            const uint8_t *peer_info_cbor,
                                            size_t len,
                                            struct RNAPIRnError *err);

int32_t rn_keys_new(void **out_keys, struct RNAPIRnError *err);

void rn_keys_free(void *keys);

int32_t rn_keys_node_get_public_key(void *keys,
                                    uint8_t **out,
                                    size_t *out_len,
                                    struct RNAPIRnError *err);

int32_t rn_keys_node_get_node_id(void *keys,
                                 char **out_str,
                                 size_t *out_len,
                                 struct RNAPIRnError *err);

int32_t rn_keys_node_generate_csr(void *keys,
                                  uint8_t **out_st_cbor,
                                  size_t *out_len,
                                  struct RNAPIRnError *err);

int32_t rn_keys_mobile_process_setup_token(void *keys,
                                           const uint8_t *st_cbor,
                                           size_t st_len,
                                           uint8_t **out_ncm_cbor,
                                           size_t *out_len,
                                           struct RNAPIRnError *err);

int32_t rn_keys_node_install_certificate(void *keys,
                                         const uint8_t *ncm_cbor,
                                         size_t ncm_len,
                                         struct RNAPIRnError *err);

int32_t rn_keys_node_export_state(void *keys,
                                  uint8_t **out_state_cbor,
                                  size_t *out_len,
                                  struct RNAPIRnError *err);

int32_t rn_keys_node_import_state(void *keys,
                                  const uint8_t *state_cbor,
                                  size_t state_len,
                                  struct RNAPIRnError *err);

int32_t rn_keys_mobile_export_state(void *keys,
                                    uint8_t **out_state_cbor,
                                    size_t *out_len,
                                    struct RNAPIRnError *err);

int32_t rn_keys_mobile_import_state(void *keys,
                                    const uint8_t *state_cbor,
                                    size_t state_len,
                                    struct RNAPIRnError *err);

int32_t rn_transport_new_with_keys(void *keys,
                                   const uint8_t *options_cbor,
                                   size_t options_len,
                                   void **out_transport,
                                   struct RNAPIRnError *err);

void rn_transport_free(void *transport);

int32_t rn_transport_start(void *transport, struct RNAPIRnError *err);

int32_t rn_transport_poll_event(void *transport,
                                uint8_t **out_event,
                                size_t *out_len,
                                struct RNAPIRnError *err);

int32_t rn_transport_connect_peer(void *transport,
                                  const uint8_t *peer_info_cbor,
                                  size_t len,
                                  struct RNAPIRnError *err);

int32_t rn_transport_disconnect_peer(void *transport,
                                     const char *peer_node_id,
                                     struct RNAPIRnError *err);

int32_t rn_transport_is_connected(void *transport,
                                  const char *peer_node_id,
                                  bool *out_connected,
                                  struct RNAPIRnError *err);

int32_t rn_transport_update_local_node_info(void *transport,
                                            const uint8_t *node_info_cbor,
                                            size_t len,
                                            struct RNAPIRnError *err);

int32_t rn_transport_request(void *transport,
                             const char *path,
                             const char *correlation_id,
                             const uint8_t *payload,
                             size_t payload_len,
                             const char *dest_peer_id,
                             const uint8_t *profile_pk,
                             size_t pk_len,
                             struct RNAPIRnError *err);

int32_t rn_transport_publish(void *transport,
                             const char *path,
                             const char *correlation_id,
                             const uint8_t *payload,
                             size_t payload_len,
                             const char *dest_peer_id,
                             struct RNAPIRnError *err);

int32_t rn_transport_complete_request(void *transport,
                                      const char *request_id,
                                      const uint8_t *response_payload,
                                      size_t len,
                                      const uint8_t *profile_pk,
                                      size_t pk_len,
                                      struct RNAPIRnError *err);

int32_t rn_transport_stop(void *transport, struct RNAPIRnError *err);

int32_t rn_transport_local_addr(void *transport,
                                char **out_str,
                                size_t *out_len,
                                struct RNAPIRnError *err);

#endif /* RUNAR_FFI_H */

// End of runar_ffi
