[package]
name = "test_service_info"
version = "0.1.0"
edition = "2021"
description = "Test package for service information"
publish = false

[dependencies]
kagi_node = { path = "../node" }
anyhow = "1.0"
