[package]
name = "runar_keys"
version = "0.1.0"
edition = "2021"
authors = ["Runar Team"]
description = "Runar Keys"
license = "MIT"

[dependencies]
async-trait = "0.1"
rusqlite = { version = "0.31.0", features = ["bundled-sqlcipher"] }
anyhow = "1.0"
thiserror = "1.0"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] } # for crud_sqlite.rs
uuid = { version = "1.8", features = ["v4", "serde"] } # Added for crud_sqlite.rs
futures = "0.3"
tokio = { version = "1.37", features = ["sync", "rt", "macros"] }
runar_common = { path = "../runar-common", features = ["abstract_service"] }

# Cryptography dependencies for runar-keys POC
ed25519-dalek = { version = "2.1.1", features = ["serde", "rand_core", "std"] } # For Ed25519 operations, version 2.x is common
ed25519-hd-key = "^0.3.0" # As specified in keys-management.md (check for latest compatible version)
sha2 = "0.10" # For SHA-256 hashing
rand = "0.8" # For random data generation
hex = "0.4" # For hex encoding/decoding of keys/signatures

# ECDH and Symmetric Encryption
x25519-dalek = { version = "2.0.0", features = ["static_secrets"] }
chacha20poly1305 = "0.10.1"
aead = "0.5.2"

# Symmetric encryption dependencies
hkdf = "0.12" # For HKDF
aes-gcm = "0.10" # For AES-GCM encryption
serde_json = "1.0" # For JSON serialization/deserialization

# TLS/QUIC dependencies - X.509 Certificate Support
rustls = { version = "0.23.28", features = [] } # For QUIC transport
rustls-pki-types = "1.12.0" # For Rustls certificate types

# X.509 certificate handling
rcgen = "0.12" # For generating X.509 certificates
x509-parser = "0.15" # For X.509 certificate parsing
der = { version = "0.7.8", features = ["derive", "pem"] }
time = { version = "0.3.34", features = ["formatting", "parsing"] }
# PKCS#10 CSR handling
pkcs1 = "0.7"
pkcs8 = "0.10"
spki = "0.7"
p256 = { version = "0.13", features = ["ecdsa"] }

keyring = "2.3"

[dev-dependencies]
tempfile = "3.10"
tokio = { version = "1.37", features = ["macros", "rt-multi-thread", "sync", "test-util"] }
runar_common = { path = "../runar-common", features = ["abstract_service"] }
runar_macros = { path = "../runar-macros" }
serde_json = "1.0"
# These are required for integration tests in tests/rusqlite_examples.rs
