[package]
name = "runar-serializer"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Enhanced serialization with selective field encryption for Runar"
license.workspace = true
license-file.workspace = true

[dependencies]
runar_common = { path = "../runar-common" }
runar-keys = { path = "../runar-keys" }
runar-serializer-macros = { path = "../runar-serializer-macros" }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
bincode = "1.3"
log = { workspace = true } 