[package]
name = "runar-nodejs-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
license-file.workspace = true

[dependencies]
