/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Ca {
  getCertificate(): Uint8Array
  getPublicKey(): Uint8Array
  getSki(): string
  getSubject(): string
  getIssuer(): string
  getSerialNumber(): string
  getValidityPeriod(): [number, number]
  isCa(): boolean
  getKeyUsage(): Array<string>
  getExtendedKeyUsage(): Array<string>
  verify(issuerCert: Ca): boolean
  free(): void
}

export declare class CaClient {
  constructor(configCbor: Uint8Array, nodeKeys: Keys)
  enroll(bootstrapAddr: string, requestCbor: Uint8Array): Promise<Uint8Array>
  renew(authenticatedAddr: string, requestCbor: Uint8Array): Promise<Uint8Array>
  revoke(authenticatedAddr: string, requestCbor: Uint8Array): Promise<Uint8Array>
  getChain(bootstrapAddr: string, networkId: string): Promise<Uint8Array>
  getStatus(authenticatedAddr: string, networkId: string): Promise<Uint8Array>
  getCrl(authenticatedAddr: string, networkId: string): Promise<Uint8Array>
  free(): void
}

export declare class CaCreator {
  static createRootCa(subject: string): Ca
  static createIssuingCa(rootCa: Ca, subject: string, validityDays: number, serial: number): Ca
  static createEaKey(): Uint8Array
  static getEaPublicKey(eaPrivateKeyDer: Uint8Array): Uint8Array
}

export declare class CaNode {
  constructor()
  /** Create new shared CA Node (following FFI pattern exactly) */
  static newShared(): CaNodeShared
  installIssuingCa(caCertDer: Uint8Array): void
  setupComplete(rootCaSubject: string, issuingCaSubject: string, validityDays: number, issuingCaSerial: number, eaPublicKeys: Uint8Array, networkId: string): void
  getRootCaCertificate(): Uint8Array
  getIssuingCaCertificate(): Promise<Uint8Array>
  handleEnroll(requestCbor: Uint8Array): Promise<Uint8Array>
  handleRenew(requestCbor: Uint8Array): Promise<Uint8Array>
  handleRevoke(requestCbor: Uint8Array): Promise<Uint8Array>
  getChain(): Promise<Uint8Array>
  getStatus(): Promise<Uint8Array>
  getCrl(): Promise<Uint8Array>
  addAdminSki(adminSki: string): Promise<void>
  revokeToken(token: string): Promise<void>
  generateCrl(): Promise<Uint8Array>
  createShared(): CaNodeShared
  /** Free CA Node resources (following FFI pattern) */
  free(): void
  configureEnrollmentAuthority(eaPublicKeysCbor: Uint8Array): Promise<void>
}

export declare class CaNodeShared {
  addAdminSki(adminSki: string): void
  /** Setup shared CA Node (following FFI pattern) */
  setupComplete(rootCaSubject: string, issuingCaSubject: string, validityDays: number, issuingCaSerial: number, eaPublicKeys: Uint8Array, networkId: string): Promise<void>
  /** Configure enrollment authority (following FFI pattern) */
  configureEnrollmentAuthority(eaPublicKeysCbor: Uint8Array): Promise<void>
  /** Get root CA certificate (following FFI pattern) */
  getRootCaCertificate(): Uint8Array
  /** Get issuing CA certificate (following FFI pattern) */
  getIssuingCaCertificate(): Promise<Uint8Array>
  /** Handle enrollment request (following FFI pattern) */
  handleEnroll(requestCbor: Uint8Array, remoteAddr: string): Promise<Uint8Array>
  /** Handle renewal request (following FFI pattern) */
  handleRenew(requestCbor: Uint8Array, peerCertDer: Uint8Array): Promise<Uint8Array>
  /** Handle revocation request (following FFI pattern) */
  handleRevoke(requestCbor: Uint8Array, peerSki: string): Promise<Uint8Array>
  /** Handle chain request (following FFI pattern) */
  handleChain(networkId: string): Promise<Uint8Array>
  /** Handle status request (following FFI pattern) */
  handleStatus(networkId: string): Promise<Uint8Array>
  /** Handle CRL request (following FFI pattern) */
  handleCrl(networkId: string): Promise<Uint8Array>
  /** Revoke token (following FFI pattern) */
  revokeToken(tokenId: string): Promise<void>
  /** Generate CRL-lite (following FFI pattern) */
  generateCrlLite(): Promise<Uint8Array>
  /** Free shared CA Node resources (following FFI pattern) */
  free(): void
}

export declare class CaServer {
  constructor(configCbor: Uint8Array, sharedCaNode: CaNodeShared)
  start(): Promise<void>
  stop(): Promise<void>
  getBootstrapAddr(): Promise<string>
  getAuthenticatedAddr(): Promise<string>
  configureAdminSkis(adminSkisCbor: Uint8Array): Promise<void>
  free(): void
}

export declare class Certificate {
  /** Extract SKI (Subject Key Identifier) from DER-encoded certificate */
  static extractSki(certDer: Uint8Array): string
  /** Extract serial number from DER-encoded certificate */
  static getSerial(certDer: Uint8Array): string
}

export declare class Discovery {
  constructor(keys: Keys, optionsCbor: Uint8Array)
  init(optionsCbor: Uint8Array): Promise<void>
  bindEventsToTransport(transport: Transport): Promise<void>
  startAnnouncing(): Promise<void>
  stopAnnouncing(): Promise<void>
  shutdown(): Promise<void>
  updateLocalPeerInfo(peerInfoCbor: Uint8Array): Promise<void>
}

export declare class EnrollmentToken {
  static generate(eaKeyDer: Uint8Array, networkId: string, subjectHint: string | undefined | null, validityDays: number, permissions: Array<string>): Uint8Array
  static validate(tokenCbor: Uint8Array, networkId: string, eaPublicKey: Uint8Array): boolean
  static getTokenInfo(tokenCbor: Uint8Array): Uint8Array
}

export declare class Keys {
  constructor()
  /**
   * Initialize this instance as a mobile manager
   * Returns error if already initialized with different type
   */
  initAsMobile(): void
  /**
   * Initialize this instance as a node manager
   * Returns error if already initialized with different type
   * CORRECTED: Only creates the key manager, nothing else
   */
  initAsNode(): void
  setPersistenceDir(dir: string): void
  /**
   * Check if node has keys loaded (replaces get_keystore_state)
   * Returns true if keys are loaded and ready, false otherwise
   */
  hasKeys(): boolean
  nodeGetKeystoreState(): number
  mobileGetKeystoreState(): number
  /**
   * Generate keys for node (explicit key generation when no state exists)
   * Returns error if keys already exist or if generation fails
   */
  generateKeys(): void
  nodeGenerateKeys(): void
  mobileInitializeUserRootKey(): Promise<void>
  /**
   * Encrypt data using envelope encryption with mobile manager
   *
   * This function encrypts data for a specific network and profile public keys
   * using the mobile key manager's envelope encryption.
   */
  mobileEncryptWithEnvelope(data: Uint8Array, networkPublicKey: Uint8Array | undefined | null, profilePublicKeys: Array<Uint8Array>): Uint8Array
  /**
   * Encrypt data using envelope encryption with node manager
   *
   * This function encrypts data for a specific network and profile public keys
   * using the node key manager's envelope encryption.
   */
  nodeEncryptWithEnvelope(data: Uint8Array, networkPublicKey: Uint8Array | undefined | null, profilePublicKeys: Array<Uint8Array>): Uint8Array
  /** Decrypt data using envelope decryption with node manager */
  nodeDecryptWithEnvelope(encryptedData: Uint8Array): Uint8Array
  nodeGetNodeId(): string
  nodeGetPublicKey(): Uint8Array
  enableAutoPersist(enabled: boolean): void
  wipePersistence(): Promise<void>
  flushState(): Promise<void>
  getKeystoreCaps(): DeviceKeystoreCaps
  encryptLocalData(data: Uint8Array): Uint8Array
  decryptLocalData(data: Uint8Array): Uint8Array
  mobileDecryptEnvelope(eedCbor: Uint8Array): Uint8Array
  nodeDecryptEnvelope(eedCbor: Uint8Array): Uint8Array
  nodeGenerateCsr(): Uint8Array
  nodeGenerateCsrDer(): Uint8Array
  mobileProcessSetupToken(stCbor: Uint8Array): Uint8Array
  nodeInstallCertificate(ncmCbor: Uint8Array): void
  mobileGenerateNetworkDataKey(): Uint8Array
  mobileInstallNetworkPublicKey(networkPk: Uint8Array): void
  nodeInstallNetworkKey(nkmCbor: Uint8Array): void
  setLocalNodeInfo(nodeInfoCbor: Uint8Array): void
  encryptForNetwork(data: Uint8Array, networkPublicKey: Uint8Array): Uint8Array
  decryptNetworkData(eedCbor: Uint8Array): Uint8Array
  encryptMessageForMobile(message: Uint8Array, mobilePk: Uint8Array): Uint8Array
  decryptMessageFromMobile(encrypted: Uint8Array): Uint8Array
  mobileDeriveUserProfileKey(label: string): Uint8Array
  mobileHasNetworkPrivateKey(networkPublicKey: Uint8Array): boolean
  mobileCreateNetworkKeyMessage(networkPublicKey: Uint8Array, nodeAgreementPk: Uint8Array): Uint8Array
  ensureSymmetricKey(keyName: string): Uint8Array
  /**
   * Get the user public key after mobile initialization
   * This is essential for encrypting setup tokens to the mobile
   */
  mobileGetUserPublicKey(): Uint8Array
  mobileGetPublicKey(): Uint8Array
  /**
   * Get the node agreement public key
   * This is used for verifying agreement keys in CSR flow
   */
  nodeGetAgreementPublicKey(): Uint8Array
  /** Convert CA Node enrollment response to NodeCertificateMessage format for certificate installation */
  mobileFromEnrollResponse(responseCbor: Uint8Array): Uint8Array
  /** Convert CA Node renewal response to NodeCertificateMessage format for certificate installation */
  mobileFromRenewResponse(responseCbor: Uint8Array): Uint8Array
  /**
   * Derive user profile key using node manager (for mobile role)
   * This is used when the node is acting as a mobile device
   */
  nodeDeriveUserProfileKey(label: string): Uint8Array
  /**
   * Decrypt data using profile key (for mobile role)
   * This is used when the node is acting as a mobile device
   */
  nodeDecryptWithProfile(envelopeCbor: Uint8Array, profileId: string): Uint8Array
  /** Extract SKI (Subject Key Identifier) from DER-encoded certificate */
  static certificateExtractSki(certDer: Uint8Array): string
  /** Extract serial number from DER-encoded certificate */
  static certificateGetSerial(certDer: Uint8Array): string
  /**
   * Get node certificate (for QUIC mTLS)
   * Returns the DER-encoded node certificate
   */
  nodeGetNodeCertificate(): Uint8Array
  /**
   * Get QUIC certificate configuration
   * Returns CBOR-encoded QUIC certificate configuration
   */
  nodeGetQuicCertificateConfig(): Uint8Array
}

export declare class Transport {
  /**
   * Create new Transport with QuicTransport backend
   * Following FFI pattern exactly - bridge callbacks to polling channels
   */
  constructor(keys: Keys, options: TransportOptions)
  /** Start the transport */
  start(): Promise<void>
  /** Stop the transport */
  stop(): Promise<void>
  /**
   * Poll for events (internal - called by TypeScript wrapper)
   * Returns CBOR-encoded event or null
   */
  pollEvent(): Promise<Buffer | null>
  /** Complete a pending request (internal - called by TypeScript wrapper) */
  completeRequest(requestId: string, payload: Buffer, profilePublicKeys: Array<Buffer>): Promise<void>
  /** Send a request and wait for response */
  request(path: string, correlationId: string, payload: Buffer, destPeerId: string, networkPublicKey: Buffer | undefined | null, profilePublicKeys: Array<Buffer>): Promise<Buffer>
  /** Publish an event */
  publish(path: string, correlationId: string, payload: Buffer, destPeerId: string, networkPublicKey?: Buffer | undefined | null): Promise<void>
  /** Connect to a peer */
  connectPeer(peerInfoCbor: Buffer): Promise<void>
  /** Check if connected to a peer */
  isConnected(peerId: string): Promise<boolean>
  /** Get local address */
  getLocalAddr(): string
  /** Update local node info - stores locally and notifies peers */
  updateLocalNodeInfo(nodeInfoCbor: Buffer): Promise<void>
}

/** Utility functions for common operations */
export declare class Utils {
  /** Calculate compact ID from public key (following FFI pattern) */
  static compactId(publicKey: Uint8Array): string
}

export interface DeviceKeystoreCaps {
  version: number
  flags: number
}

export interface EventEnvelope {
  path: string
  correlationId: string
  payload: Uint8Array
  sourceNodeId: string
  destinationNodeId: string
  profilePublicKeys: Array<Uint8Array>
  networkPublicKey?: Uint8Array
}

export interface PeerConnectedEnvelope {
  peerId: string
  nodePublicKey: Uint8Array
  networkIds: Array<string>
  addresses: Array<string>
  version: number
  nodeMetadata: string
}

export interface PeerDisconnectedEnvelope {
  peerId: string
}

export interface RequestEnvelope {
  requestId: string
  path: string
  correlationId: string
  payload: Uint8Array
  sourceNodeId: string
  destinationNodeId: string
  profilePublicKeys: Array<Uint8Array>
  networkPublicKey?: Uint8Array
}

/** Set node ID on root logger (following FFI pattern exactly) */
export declare function setLoggerNodeId(nodeId: string): void

/** Set the global log level (following FFI pattern exactly) */
export declare function setLogLevel(level: number): void

export interface TransportEvent {
  path: string
  correlationId: string
  payload: Uint8Array
  sourceNodeId: string
  destinationNodeId: string
  profilePublicKeys: Array<Uint8Array>
  networkPublicKey?: Uint8Array
}

export interface TransportOptions {
  bindAddr?: string
  connectionIdleTimeout?: number
  keepAliveInterval?: number
  maxMessageSize?: number
  enableRequestCallbacks?: boolean
  enableEventCallbacks?: boolean
  enablePeerCallbacks?: boolean
}

export interface TransportRequest {
  path: string
  correlationId: string
  payload: Uint8Array
  sourceNodeId: string
  destinationNodeId: string
  profilePublicKeys: Array<Uint8Array>
  networkPublicKey?: Uint8Array
}

export interface TransportResponse {
  payload: Uint8Array
  correlationId: string
}
