name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'rust-docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'rust-docs/**'
      - '.github/workflows/docs.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: |
          cd rust-docs/build
          bun install

      - name: Build Documentation
        run: |
          cd rust-docs/build
          bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./rust-docs/website
          publish_branch: gh-pages
          commit_message: ${{ github.event.head_commit.message }} 