name: Rust CI 2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Debug start
        run: echo "Workflow started successfully"

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show .gitmodules and .git/config for debugging
        run: |
          echo "---- .gitmodules ----"
          cat .gitmodules || echo "No .gitmodules"
          echo "---- .git/config ----"
          cat .git/config || echo "No .git/config"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check code format
        run: cargo fmt --all -- --check

      - name: Check with clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features

      - name: Build
        run: cargo build --verbose

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: runar-nodejs-ffi/package-lock.json

      - name: Install dependencies
        run: cd runar-nodejs-ffi && npm ci

      - name: Build Node.js FFI
        run: cd runar-nodejs-ffi && npm run build

      - name: Test Node.js FFI
        run: cd runar-nodejs-ffi && npm test