name: Rust CI 2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Debug start
        run: echo "Workflow started successfully"

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show .gitmodules and .git/config for debugging
        run: |
          echo "---- .gitmodules ----"
          cat .gitmodules || echo "No .gitmodules"
          echo "---- .git/config ----"
          cat .git/config || echo "No .gitmodules"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check code format
        run: cargo fmt --all -- --check

      - name: Check with clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: RUNAR_KEYS_LINUX_FILE_KEYSTORE=1 cargo test --all-features

      - name: Build
        run: cargo build --verbose

      - name: Build runar_ffi (generate header)
        run: cargo build -p runar_ffi --all-targets --features linux-keystore --verbose

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Node.js API dependencies
        working-directory: runar-nodejs-api
        run: bun install

      - name: Build Node.js native module
        working-directory: runar-nodejs-api
        run: bun run build

      - name: Run Node.js API tests
        working-directory: runar-nodejs-api
        run: bun tests